"""crear tabla movimientos

Revision ID: 00848d396878
Revises: 19ada97356f3
Create Date: 2026-03-04 10:36:55.212881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00848d396878'
down_revision = '19ada97356f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elemento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elemento_id'], ['elementos_inventario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    # ### end Alembic commands ###
