"""crear tabla elementos_inventario

Revision ID: 19ada97356f3
Revises: 950edaa9739b
Create Date: 2026-02-26 11:31:48.741891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ada97356f3'
down_revision = '950edaa9739b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elementos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.Enum('insumo', 'maquinaria', 'herramienta', 'material'), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elementos_inventario')
    # ### end Alembic commands ###
