"""tabla usuarios inicial

Revision ID: 347b46d715b3
Revises: 
Create Date: 2026-02-25 11:40:30.311365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '347b46d715b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('elementos_inventario')
    op.drop_table('productos')
    op.drop_table('movimientos')
    op.drop_table('clientes')
    op.drop_table('detalle_ventas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('admin', 'operario', 'consultor', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'operario'"))
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('admin', 'operario', 'consultor', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'operario'"))

    op.create_table('detalle_ventas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('precio_unit', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_det_producto')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_det_venta')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('documento', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movimientos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('elemento_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('entrada', 'salida'), nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observacion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['elemento_id'], ['elementos_inventario.id'], name=op.f('fk_mov_elemento')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_mov_usuario')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('unidad_medida', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('elementos_inventario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('categoria', mysql.ENUM('insumo', 'maquinaria', 'herramienta', 'material'), nullable=False),
    sa.Column('stock_actual', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('stock_minimo', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('unidad_medida', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ventas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=14, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_venta_cliente')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
